name: diogenes
description: An app to manage your home inventory.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Allow international texts
  intl: ^0.17.0
  # Make http requests to the backend server
  http: ^0.13.5
  # State management
  provider: ^6.0.5
  # Refetch data
  pull_to_refresh: ^2.0.0
  # Logs in the app
  logger: ^1.3.0
  # Save settings in device
  shared_preferences: ^2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
